// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2BNd1Y2MUlNlqjnfMHUnTZE_gtPaRVvA',
    appId: '1:336622508205:web:a0852be86d76768d500e24',
    messagingSenderId: '336622508205',
    projectId: 'openhattrick',
    authDomain: 'openhattrick.firebaseapp.com',
    databaseURL: 'https://openhattrick-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openhattrick.appspot.com',
    measurementId: 'G-J99001XJ13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARCsQjho3OmS1vQxgZbfQvV0aqgfpQbz0',
    appId: '1:336622508205:android:d5e751fb983bbc5c500e24',
    messagingSenderId: '336622508205',
    projectId: 'openhattrick',
    databaseURL: 'https://openhattrick-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openhattrick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkgSAgC23JkXXTEiospQN23rC3Maa3Hc',
    appId: '1:336622508205:ios:d7425b15008858a7500e24',
    messagingSenderId: '336622508205',
    projectId: 'openhattrick',
    databaseURL: 'https://openhattrick-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openhattrick.appspot.com',
    iosBundleId: 'com.example.testFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkgSAgC23JkXXTEiospQN23rC3Maa3Hc',
    appId: '1:336622508205:ios:51538415197aafc1500e24',
    messagingSenderId: '336622508205',
    projectId: 'openhattrick',
    databaseURL: 'https://openhattrick-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openhattrick.appspot.com',
    iosBundleId: 'com.example.testFlutterApp.RunnerTests',
  );
}
